//! Auto-generated FFI bindings for OpenWrt libnl-tiny and Linux kernel
//! rtnetlink UAPI.
//!
//! Generated by bindgen from `wrapper.h` at build time.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
